# Hyperparameter Tuning for K-NN Regressor
 - name: KNeighborsRegressor
   isSelected: true
   type: Regression
   datatype: Tabular
   complexity: ML
   hyper:
    - name: n_neighbors
      value: 5
      type: int
      vary: true
      ischanged: false
      options: null
      range:
         type: linear
         min: 3
         max: 100
         num_samp: 30
    - name: leaf_size
      value: 30
      type: int
      vary: true
      ischanged: false
      options: null
      range:
          type: linear
          min: 10
          max: 300
          num_samp: 30
    - name: algorithm
      value: auto
      ischanged: false
      type: option
      vary: false
      options:
        - ball_tree
        - auto
        - kd_tree
        - brute
      range: null
    # Hyperparameter tuning for DecisionTree Classifier
 - name: DecisionTreeClassifier
   isSelected: false
   type: Classification
   datatype: Tabular
   complexity: ML
   hyper:
    - name: max_depth
      value: null
      ischanged: false
      type: int # either option bool or number
      options: null
      vary: true
      range:
        type: linear
        min: 10
        max: 200
        num_samp: 20
    - name: min_samples_split
      value: 2
      ischanged: false
      type: int # either option bool or number
      options: null
      vary: true
      range:
        type: linear
        min: 10
        max: 200
        num_samp: 20
    - name: criterion
      value: gini
      ischanged: false
      vary: false
      type: option
      options:
        - entropy
        - gini
      range: null
    - name: min_samples_leaf
      value: 1
      ischanged: false
      type: int # either int or float
      options: null
      vary: true
      range:
        type: linear
        min: 5
        max: 100
        num_samp: 20
 
      # Hyperparameter tuning for RandomForest Regressor  
 - name: RandomForestRegressor
   isSelected: true
   type: Regression
   datatype: Tabular
   complexity: ML
   hyper:
    - name: criterion
      value: MSE
      ischanged: false
      vary: false
      type: option
      options: 
        - MAE # Mean Absolute Error (MAE)
        - MSE # Mean Squared Error (MSE)
      range: null
    - name: n_estimators
      value: 100
      ischanged: false
      type: int
      options: null
      vary: true
      range:
        type: linear
        min: 10
        max: 1000
        num_samp: 20
    -  name: max_depth
       value: null
       ischanged: false
       type: int
       options: null
       vary: true
       range:
        type: linear
        min: 5
        max: 100
        num_samp: 20
    - name: min_samples_split
      value: 2
      ischanged: false
      type: int # either int or float
      options: null
      vary: true
      range:
        type: linear
        min: 5
        max: 100
        num_samp: 20
  # Hyperparameter tuning for K-NN Classifier
 - name: KNeighborsClassifier
   isSelected: false
   type: Classification
   datatype: Tabular
   complexity: ML
   hyper:
    - name: n_neighbors
      value: 5
      type: int
      ischanged: false
      options: null
      vary: true
      range:
         type: linear
         min: 5
         max: 100
         num_samp: 20
    - name: leaf_size
      value: 30
      ischanged: false
      type: int
      options: null
      vary: true
      range:
          type: linear
          min: 10
          max: 300
          num_samp: 20
    - name: algorithm
      value: auto
      ischanged: false
      vary: false
      type: option
      options:
        - ball_tree
        - auto
        - kd_tree
        - brute
      range: null
  # Hyperparameter tuning for DecisionTree Regressor
 - name: DecisionTreeRegressor
   isSelected: true
   type: Regression
   datatype: Tabular
   complexity: ML
   hyper:
    - name: criterion
      value: mse
      ischanged: false
      vary: false
      type: option
      options:
        - friedman mse
        - poisson
        - mse
        - mae
      range: null
    - name: max_depth
      value: null
      ischanged: false
      type: int # either option bool or number
      options: null
      vary: true
      range:
        min: 10
        max: 500
        num_samp: 20
    - name: min_samples_split
      value: 2
      ischanged: false
      type: int # either int or float
      options: null
      vary: true
      range:
        min: 0
        max: 300
        num_samp: 50 
    # Hyperparameter tuning for XGBOOST classifier
 - name: XGBClassifier
   isSelected: false
   type: Classification
   datatype: Tabular
   complexity: ML
   hyper:
    - name: learning_rate
      value: 0.3
      ischanged: false
      type: float
      vary: true
      options: null
      range:
         type: linear
         min: 0.0
         max: 1.0
         num_samp: 20
    - name: max_depth
      value: 6
      ischanged: false
      type: int
      options: null
      vary: true
      range:
         type: linear
         min: 0
         max: 100 
         num_samp: 2
    - name: gamma
      value: 0
      ischanged: false
      type: float # either int or float
      options: null
      vary: true
      range:
         type: log
         min: 1.0e-3
         max: 1.0e+5
         num_samp: 50
  # Hyperparameter tuning for Polynomial Regressor
 - name: PolynomialRegression
   isSelected: true
   type: Regression
   datatype: Tabular
   complexity: ML
   hyper:
    - name: poly_degree
      value: 2
      ischanged: false
      type: int
      vary: true
      options: null
      range:
         type: linear
         min: 2
         max: 7
         num_samp: 5
  # Hyperparameter tuning for  GaussianNaiveBayes
 - name: GaussianNB
   isSelected: false
   type: Classification
   datatype: Tabular
   complexity: ML
   hyper:
    - name: var_smoothing
      type: float
      value: 1e-9
      ischanged: false
      vary: true
      options: null
      range: 
         type: log
         min: 1.0e-5
         max: 1.0e+4
         num_samp: 50
  # Hyperparameter tuning for MultinomialNaiveBayes
 - name: MultinomialNB
   isSelected: false
   type: Classification
   datatype: Tabular
   complexity: ML
   hyper:
    - name: alpha
      type: float
      vary: true
      value: 1.0
      ischanged: false
      options: null
      range:
         type: linear
         min: 1.0
         max: 20.0
         num_samp: 20
    - name: fit_prior
      type: bool
      vary: false
      value: True
      ischanged: false
      options: null
      range: null
  # Hyperparameter tuning for XGBOOST Regressor
 - name: XGBRegressor
   isSelected: true
   type: Regression
   datatype: Tabular
   complexity: ML
   hyper :
    - name: verbosity
      type: option
      vary: true
      value: 1
      ischanged: false
      options:
        - 0 # 0 indicates silent
        - 1 # 1 indicates warning
        - 2 # 2 indicates info
        - 3 # 3 indicates debug
      range:
         min: 0
         max: 3
    - name: booster
      value: gblinear
      ischanged: false
      vary: false
      type: option
      options:
        - gblinear
      range: null
    - name: updater # choice of algorithm to fit linear model
      value: shotgun
      ischanged: false
      vary: True
      type: option
      options:
        - shotgun
        - coord_descent
      range: null

    # Hyperparameter tuning for Logistic Classifier
 - name: LogisticRegression
   isSelected: false
   type: Classification
   data_type: Tabular
   complexity: ML
   hyper:
    - name: penalty
      vary: false
      value: 12
      ischanged: false
      type: option # either option, bool or number
      options:
        - l1
        - l2
        - elasticnet
        - none
      range: null
    - name: fit_intercept
      vary: true
      value: true
      ischanged: false
      type: bool # either option, bool or number
      options: null
      range: null
    - name: solver
      vary: false
      value: lbfgs
      ischanged: false
      type: option
      options:
        - lbfgs
        - newton-cg
      range: null
    - name: multi_class
      vary: true
      value: auto
      ischanged: false
      type: option
      options:
        - auto
        - ovr
        - multinomial
      range: null
    # Hyperparameter tuning for Linear Regressor
 - name: LinearRegression
   isSelected: true
   type: Regression
   data_type: Tabular
   complexity: ML
   hyper:
    - name: fit_intercept
      vary: true
      value: true
      ischanged: false
      type: bool # either option, bool or number
      options: null
      range: null
  # Hyperparameter tuning for SupportVector Classifier(SVC)
 - name: SVC
   isSelected: false
   type: Classification
   data_type: Tabular
   complexity: ML
   hyper:
    - name:  C
      vary: true
      value: 1.0
      ischanged: false
      type: float
      options: null 
      range:
         min:  1.0e-5
         max: 1.0e+3
         num_samp: 20
         type: log # can be log or linear
    - name: kernel
      vary: false
      value: rbf
      ischanged: false
      type: option # either option, bool or number
      options:
        - linear
        - poly
        - rbf
        - sigmoid
      range: null
    - name: gamma
      vary: true
      value: scale
      ischanged: false
      type: option # either option, bool or number
      options:
        - auto
        - scale
      range: null

  # Hyperparameter tuning for SupportVector Regressor(SVR)
 - name: SVR
   isSelected: true
   type: Regression
   data_type: Tabular
   complexity: ML
   hyper:
    - name: C
      vary: true
      value: 1.0
      ischanged: false
      type: float # either option, bool or number
      options: null
      range: 
         min: 1.0e-5
         max: 1.0e+3
         num_samp: 50
         type: log # can be log or linear
    - name: kernel
      vary: false
      value: rbf
      ischanged: false
      type: option # either option, bool or number
      options:
        - linear
        - poly
        - rbf
        - sigmoid
      range: null
    - name: gamma
      vary: true
      value: scale
      ischanged: false
      type: option # either option, bool or number
      options:
        - auto
        - scale
      range: null

  # Hyperparameter Tuning for RandomForest Classifier
 - name:  RandomForestClassifier
   isSelected: false
   type: Classification
   data_type: Tabular
   complexity: ML
   hyper: 
    - name: n_estimators
      vary: true
      value: 100
      ischanged: false
      type: int # either option, bool or number
      options: null
      range:
         min: 10
         max: 1000
         num_samp: 50
         type: linear # can be log or linear
    - name: max_depth
      vary: true
      value: null
      ischanged: false
      type: int # either option, bool or number
      options: null
      range:
         min: 5
         max: 100
         num_samp: 20
         type: linear # can be log or linear

    


       





      


 