# The address at which the user's uploaded raw data is saved.
raw_data_address:

pre-processing:
# For droping empty rows and columns
 - drop_col_name: ["none"]


# For filling null values present in the dataset.(Imputation)
 - imputation_column: ["none"]
   impution_type: []
   missing_value: 


# For feature scaling.
 - scaling_col_name: ["none"]
   scaling_type: []



# For feature scaling.
 - encode_col_name: ["none"]
   encoding_type: []


  



