# The address at which the user's uploaded raw data is saved.
raw_data_address: ""

# User specified target column.
target_column_name: ""

# For droping empty rows and columns
drop_column_name: 
- ""

# For filling null values present in the dataset.(Imputation)
imputation_column_name: 
- ""
impution_type: 
- ""

mean_median_mode_values:
- 0

na_notation : 
- ""


# For feature scaling.
scaling_column_name: 
- ""
scaling_type: 
- ""

# For feature scaling.
encode_column_name: 
- ""
encoding_type: 
- ""
labels:
- 

Remove_outlier: True

feature_selection: True

data_imbalance: False

split_ratio_test: 0.3

is_auto: True

clean_data_address:
